// Иконки для навигации - используются в мобильном и десктопном меню
import {
  FiUsers,
  FiShoppingBag,
  FiPackage,
  FiTag,
  FiLayers,
  FiTruck,
  FiGrid,
  FiHome,
  FiMessageSquare,
  FiShield,
  FiDollarSign,
  FiSettings,
  FiUser,
  FiMoon,
  FiX,
  FiFileText,
  FiBox,
  FiClipboard,
  FiRepeat,
  FiCheckSquare,
  FiPercent,
} from 'react-icons/fi';

export const Icons = {
  crm: FiUsers,
  catalog: FiGrid,
  warehouse: FiBox,
  billing: FiDollarSign,
  pricing: FiPercent,
  users: FiUsers,
  orders: FiFileText,
  customers: FiUsers,
  tickets: FiClipboard,
  chats: FiMessageSquare,
  permissions: FiShield,
  products: FiShoppingBag,
  categories: FiTag,
  manufacturers: FiPackage,
  suppliers: FiTruck,
  'product-types': FiLayers,
  attributes: FiLayers,
  'warehouse-products': FiBox,
  movements: FiRepeat,
  inventory: FiCheckSquare,
  prices: FiDollarSign,
  settings: FiSettings,
  home: FiHome,
  support: FiMessageSquare,
  dashboard: FiGrid,
  profile: FiUser,
  theme: FiMoon,
  close: FiX,
};
